#!/usr/bin/env bash
set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <cert>"
  exit 0
fi

ca_cert=$1
ca_cert_alias='ca'

keystore_location=${JAVA_HOME}/jre/lib/security/cacerts
if test ! -f "$keystore_location"; then
    keystore_location=${JAVA_HOME}/lib/security/cacerts
fi
keystore_password=changeit

cd ${JAVA_HOME}/bin
./keytool -noprompt -keystore ${keystore_location} -storepass ${keystore_password} -alias ${ca_cert_alias} -delete || true
./keytool -noprompt -keystore ${keystore_location} -storepass ${keystore_password} -alias ${ca_cert_alias} -importcert -file ${ca_cert}

